SET NAMES utf8;

DELETE FROM `trinity_string` WHERE `entry` BETWEEN 12100 AND 12199;
INSERT INTO `trinity_string` (`entry`,`content_default`) VALUES
(12100, 'You are jailed by %s for %u hour(s)!'),
(12101, '%s wrote this as reason: %s'),
(12102, '%s was jailed by you for %u hour(s).'),
(12103, 'You was released out of the jail by %s.'),
(12104, 'You have released %s out of the jail.'),
(12105, 'No reason given or reason is < %u chars!'),
(12106, 'No name given!'),
(12107, 'No time given!'),
(12108, 'The jailtime must be between 1 and %u hours!'),
(12109, 'The character %s is not jailed!'),
(12110, 'Command forbidden for jailed characters!'),
(12111, 'You have %u hour(s) and %u minute(s) left in your jailtime.'),
(12112, 'You have %u minute(s) left in your jailtime.'),
(12113, 'You are free like a bird! ;-)'),
(12114, '%s was %u times jailed and has %u minute(s) left.\nLast time jailed by: %s.\nThe last jail was on: %s\nThe last reason was: %s'),
(12115, '%s was never jailed.'),
(12116, 'You can not jail yourself!'),
(12117, 'You can not unjail yourself!'),
(12118, 'Be carefull!\nOnly one more jailtime and your current character will be deleted!'),
(12119, 'The character %s was jailed for %u hour(s) by the GM %s!\nThe reason is: %s'),
(12120, 'Jail: The Configuration was reloaded.'),
(12121, 'Jail: Configuration loaded.'),
(12122, 'Jail: Can not load the Configuration! The jail db table is corrupt'),
(12123, 'Jail: Set all config settings to default values.'),
(12124, 'The Character %s (GUID %u) is a jail inmate and teleported into the jail.'),
(12125, 'The Character %s (GUID %u) was released out of the jail.'),
(12126, 'A character with this name does not exist!'),
(12127, 'Be carefull!\nOnly one more jailtime and your account will be banned!'),
(12128, 'Max. jailtimes reached!'),
(12129, 'You are previously convicted and jailed but now released.'),
(12130, '%s was %u times jailed and has %u hour(s) and %u minute(s) left.\nLast time jailed by: %s.\nThe last jail was on: %s\nThe last reason was: %s'),
(12131, '%s was multiple times jailed and has already %u bans!'),
(12132, 'The account of this character has %u ban(s)!'),
(12133, '%s is already in Jail!'),
(12134, 'You can not reset a Jail entry with a banned account use delete command instead!'),
(12135, 'Jail: Jail data reloaded.'),
(12136, 'Jail: Delete entries with no longer existing characters.'),
(12137, 'Jail: Checking the jail for outdated arrests...'),
(12138, 'Jail: No arrests found.'),
(12139, 'Jail: %u outdated arrests found and within %u ms checked.'),
(12140, 'Jail: Initialize the jail...'),
(12141, 'Jail: The Jail isnt active! Terminating initialization.'),
(12142, 'Jail: No arrests found.'),
(12143, 'Jail: %u arrests (%u are active) within %u ms loaded.'),
(12144, 'ERROR! STRING TO LONG!'),
(12145, 'Jail: Jail data loaded.'),
(12146, 'No faction (horde/ally) given!'),
(12197, 'The Jail is now active.'),
(12198, 'The Jail is now inactive.'),
(12199, 'The Jail is not active!');
